In [1]:
import pandas as pd
import numpy as np

In [26]:
data1 = pd.read_csv('data/أدبي.csv')
data2 = pd.read_csv('data/علمي.csv')
data3 = pd.read_csv("datanotebook1.csv")

In [7]:
list(data1.columns) == list(data1.columns)

True

In [10]:
x = list(data1.columns)
x

['معدلك في الثانوية العامة',
 'نوع المدرسة',
 'الوضع الاقتصادي',
 'طبيعة عمل ولي الامر',
 'طبيعة السكن',
 'هل كنت تمتلك جهاز حاسوب',
 'هل يمتلك ولي أمرك وسيلة نقل خاصة',
 'التحصيل العلمي للوالد',
 'التحصيل العلمي للوالدة',
 'نوع الجامعة',
 'مشاكل في النظر',
 'مشاكل في السمع',
 'مشاكل جسدية',
 'لا يوجد مشاكل',
 'الرياضة هوايتي',
 'القراءة هوايتي',
 'الكتابة هوايتي',
 'التحليل هوايتي',
 'حل المسائل هوايتي',
 'التكنولوجيا هوايتي',
 'لا يوجد هواية',
 'كليتك؟']

In [37]:
data1[x[6]].unique()

array([1, 0])

In [38]:
data2[x[6]].unique()

array([0., 1.])

In [47]:
data3[x[10]].unique()

array([1, 0])

In [60]:
x[22]

IndexError: list index out of range